7 Вариант
![title](lab2.png)

In [2]:
import numpy
from scipy import linalg
import math
import matplotlib.pyplot as plt
%matplotlib inline

p = [1.0, 0.1, 0.01, 0.0001, 0.000001]

A = numpy.matrix([[ 0,  2,  8, -7,  7,  5, -7, -7],
                 [  7,  2, -4,  2,  3,  3, -1, -2],
                 [ -7,  2,  1,  3,  6, -6, -3, -4],
                 [ -2, -8, -6, -1,  6,  2,  1, -4],
                 [  0,  4, -7,  1, 22,  0, -6, -6],
                 [  0, -3, -6,  6,  4, 13,  0,  6],
                 [ -8, -6, -4,  7, -5, -5, -2,  1],
                 [  5,  5, -2, -2, -3,  0, -7, 14]])

b = numpy.matrix([[6.0], [36], [-25], [-57], [32], [62], [-71], [70]])

In [5]:
roots = []
for delta in p:
    A[0, 0] = 13 + delta # + B ??? 
    b[0, 0] = 6 + 4 * delta
    print('p =', delta)
    print("A[0,0]: ", A[0,0])
    print("b[0,0]: ", b[0,0])
    print('x1: \n', numpy.linalg.solve(A, b), "\n")
    roots.append(numpy.linalg.solve(A, b)[0])
    Anew = A.transpose() * A
    bnew = A.transpose() * b
    print('x2: \n', numpy.linalg.solve(Anew, bnew), "\n")
    print('delta:\n', (numpy.linalg.solve(A,b) - numpy.linalg.solve(Anew, bnew) / numpy.linalg.solve(Anew, bnew)))
    print('cond =' , numpy.linalg.cond(A))

p = 1.0
A[0,0]:  14
b[0,0]:  10.0
x1: 
 [[4.]
 [5.]
 [2.]
 [4.]
 [4.]
 [1.]
 [5.]
 [6.]] 

x2: 
 [[4.]
 [5.]
 [2.]
 [4.]
 [4.]
 [1.]
 [5.]
 [6.]] 

delta:
 [[3.00000000e+00]
 [4.00000000e+00]
 [1.00000000e+00]
 [3.00000000e+00]
 [3.00000000e+00]
 [3.09974268e-13]
 [4.00000000e+00]
 [5.00000000e+00]]
cond = 2740.211288275447
p = 0.1
A[0,0]:  13
b[0,0]:  6.4
x1: 
 [[-1.05901219e+13]
 [ 1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]
 [ 1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]] 

x2: 
 [[10.2618706 ]
 [-1.2696686 ]
 [ 8.27286843]
 [10.25854661]
 [10.25554597]
 [-5.24957686]
 [11.23277689]
 [12.25      ]] 

delta:
 [[-1.05901219e+13]
 [ 1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]
 [ 1.05901219e+13]
 [-1.05901219e+13]
 [-1.05901219e+13]]
cond = 5.28818005213761e+16
p = 0.01
A[0,0]:  13
b[0,0]:  6.04
x1: 
 [[-1.05901219e+12]
 [ 1.05901219e+12]
 [-1.05901219e+12]
 [-1.05901219e+12]
 [-1.05901219e+12]
 [ 1.05901219e+12]
 [-1.05